org: basepi
app: serverless-testing
service: serverless-testing

frameworkVersion: '2'

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: false

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing
