org: basepi
app: serverless-testing-basepi
service: serverless-testing-basepi

frameworkVersion: "3"

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: false
    invalidateCaches: true
    useStaticCache: false
    useDownloadCache: false

provider:
  name: aws
  runtime: python3.8
  environment:
    ELASTIC_APM_SERVICE_NAME: serverless-testing-basepi
    ELASTIC_APM_LAMBDA_APM_SERVER: "https://115e71c05a64444bb6f027072aa739e4.apm.us-central1.gcp.cloud.es.io:443"
    ELASTIC_APM_SECRET_TOKEN: "<redacted>"

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:267093732750:layer:elastic-apm-extension-ver-1-1-0-x86_64:1
    events:
      - http:
          path: /
          method: get
      - s3: basepitestbucket2
      - sns: basepitestsnstopic

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing
